<x-layouts.app title="Staff Dashboard" :heading="'Dashboard'" :subheading="now()->format('l, F j, Y')">
    <div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
        <x-stat-card variant="solid" label="My Sales Today" value="₱{{ number_format($salesToday, 2) }}" :hint="$transactionsToday.' transactions recorded'" icon="dollar" color="primary" />
        <x-stat-card variant="solid" label="Delivery Queue" :value="$pendingDeliveries" hint="Pending or confirmed" icon="truck" color="delivery" />
        <x-stat-card variant="solid" label="Out for Delivery" :value="$outForDelivery" hint="Currently in transit" icon="truck" color="secondary" />
        <x-stat-card variant="solid" label="Low Stock Alerts" :value="$lowStockProducts + $lowStockConsumables" hint="Products and supplies" icon="alert-triangle" color="warning" />
    </div>

    <div class="mt-6 flex flex-wrap gap-3"><x-button as="a" href="{{ route('pos.create') }}"><x-icon name="plus" class="size-4" /> Record a Sale</x-button><x-button as="a" href="{{ route('deliveries.index') }}" variant="secondary"><x-icon name="truck" class="size-4" /> Delivery Queue</x-button><x-button as="a" href="{{ route('payments.index') }}" variant="secondary"><x-icon name="credit-card" class="size-4" /> Customer Payments</x-button></div>

    <div class="mt-6 grid gap-6 lg:grid-cols-3">
        <x-card class="overflow-hidden lg:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-heading text-base font-bold text-slate-900 dark:text-white">My Sales Activity</h2><p class="text-xs text-slate-400">Sales you recorded in the last seven days</p></div><span class="rounded-xl bg-primary-50 p-2 text-primary-600 dark:bg-primary-500/10 dark:text-primary-300"><x-icon name="chart" class="size-5" /></span></div><div class="relative mt-5 h-72 rounded-2xl border border-slate-100 bg-slate-50/70 p-3 dark:border-white/5 dark:bg-slate-950/30"><canvas id="staffSalesChart" class="block size-full" aria-label="Staff sales chart"></canvas></div></x-card>
        <x-card padding="p-0"><div class="flex items-center justify-between px-6 py-4"><div><h2 class="font-heading text-base font-bold text-slate-900 dark:text-white">Priority Deliveries</h2><p class="text-xs text-slate-400">Orders requiring attention</p></div><a href="{{ route('deliveries.index') }}" class="text-xs font-semibold text-primary-600 hover:text-primary-700">View all</a></div><div class="divide-y divide-slate-100 dark:divide-white/5">@forelse($priorityDeliveries as $order)<a href="{{ route('deliveries.show', $order) }}" class="block px-6 py-3 transition hover:bg-slate-50 dark:hover:bg-white/5"><div class="flex items-center justify-between gap-2"><p class="font-mono text-xs font-semibold text-primary-600">{{ $order->order_code }}</p><x-delivery-status-badge :status="$order->status" /></div><p class="mt-1 truncate text-sm font-medium text-slate-900 dark:text-white">{{ $order->customer_name }}</p><p class="truncate text-xs text-slate-400">{{ $order->product_name }} × {{ $order->quantity }} · {{ $order->preferred_delivery_date?->format('M d') ?? 'No date' }}</p></a>@empty<p class="px-6 pb-6 text-sm text-slate-500 dark:text-slate-400">No active delivery orders.</p>@endforelse</div></x-card>
    </div>

    <x-card class="mt-6" padding="p-0"><div class="flex items-center justify-between px-6 py-4"><div><h2 class="font-heading text-base font-bold text-slate-900 dark:text-white">My Recent Transactions</h2><p class="text-xs text-slate-400">Only sales recorded under your staff account</p></div><a href="{{ route('pos.index') }}" class="text-sm font-semibold text-primary-600 hover:text-primary-700">View all</a></div>@if($recentTransactions->isEmpty())<div class="px-6 pb-6"><x-empty-state icon="cart" title="No sales recorded yet" description="Sales you record will appear here." /></div>@else<div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 dark:divide-white/10"><thead class="bg-slate-50/80 dark:bg-white/[0.03]"><tr class="text-left text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400"><th class="px-6 py-3">Transaction</th><th class="px-6 py-3">Customer</th><th class="px-6 py-3">Type</th><th class="px-6 py-3">Payment</th><th class="px-6 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-white/5">@foreach($recentTransactions as $transaction)<tr class="transition hover:bg-slate-50/80 dark:hover:bg-white/[0.03]"><td class="px-6 py-3"><a href="{{ route('pos.show', $transaction) }}" class="font-mono text-sm font-semibold text-primary-600">{{ $transaction->transaction_code }}</a></td><td class="px-6 py-3 text-sm text-slate-700 dark:text-slate-300">{{ $transaction->customer_name ?? $transaction->customer?->name ?? 'Walk-in guest' }}</td><td class="px-6 py-3"><x-badge :color="$transaction->transaction_type === 'delivery' ? 'delivery' : 'primary'">{{ $transaction->transaction_type === 'delivery' ? 'Delivery' : 'Walk-in' }}</x-badge></td><td class="px-6 py-3"><x-badge :color="$transaction->payment_method === 'loan' ? 'warning' : 'success'">{{ ucfirst($transaction->payment_method) }}</x-badge></td><td class="px-6 py-3 text-right font-mono text-sm font-semibold text-slate-900 dark:text-white">₱{{ number_format($transaction->total_amount, 2) }}</td></tr>@endforeach</tbody></table></div>@endif</x-card>

    @push('scripts')<script>document.addEventListener('DOMContentLoaded', () => { const dark = document.documentElement.classList.contains('dark'); const chart = new window.Chart(document.getElementById('staffSalesChart'), { type: 'line', data: { labels: @json($salesTrendLabels), datasets: [{ data: @json($salesTrendData), label: 'Sales', borderColor: '#0ea5e9', backgroundColor: 'rgba(14, 165, 233, 0.12)', borderWidth: 2.5, tension: 0.35, fill: true, pointRadius: 3, pointBackgroundColor: '#0ea5e9' }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false }, tooltip: { backgroundColor: dark ? '#0f172a' : '#fff', titleColor: dark ? '#f8fafc' : '#0f172a', bodyColor: dark ? '#cbd5e1' : '#475569', borderColor: dark ? 'rgba(148,163,184,.2)' : 'rgba(15,23,42,.12)', borderWidth: 1 } }, scales: { x: { ticks: { color: dark ? '#94a3b8' : '#475569' }, grid: { color: dark ? 'rgba(148,163,184,.15)' : 'rgba(100,116,139,.1)' } }, y: { beginAtZero: true, ticks: { color: dark ? '#94a3b8' : '#475569' }, grid: { color: dark ? 'rgba(148,163,184,.15)' : 'rgba(100,116,139,.1)' } } } } }); new MutationObserver(() => { const isDark = document.documentElement.classList.contains('dark'); const text = isDark ? '#94a3b8' : '#475569'; const grid = isDark ? 'rgba(148,163,184,.15)' : 'rgba(100,116,139,.1)'; chart.options.scales.x.ticks.color = text; chart.options.scales.y.ticks.color = text; chart.options.scales.x.grid.color = grid; chart.options.scales.y.grid.color = grid; chart.update(); }).observe(document.documentElement, { attributes: true, attributeFilter: ['class'] }); });</script>@endpush
</x-layouts.app>
