<x-layouts.app title="My Dashboard" :heading="'Welcome back, '.auth()->user()->name" :subheading="'Manage your deliveries, payments, and account balance'">
    <div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
        <x-stat-card variant="solid" label="Outstanding Balance" value="₱{{ number_format(auth()->user()->credit_balance, 2) }}" :hint="auth()->user()->credit_balance > 0 ? 'Payment can be recorded by staff' : 'Your account is settled'" icon="credit-card" :color="auth()->user()->credit_balance > 0 ? 'warning' : 'success'" />
        <x-stat-card variant="solid" label="Total Orders" :value="$totalOrders" hint="All delivery orders" icon="truck" color="primary" />
        <x-stat-card variant="solid" label="Active Orders" :value="$pendingOrders" hint="Being processed" icon="clock" color="delivery" />
        <x-stat-card variant="solid" label="Total Spent" value="₱{{ number_format($totalSpent, 2) }}" hint="Completed purchases" icon="dollar" color="secondary" />
    </div>

    <div class="mt-6 flex flex-wrap gap-3"><x-button as="a" href="{{ route('customer.orders.create') }}"><x-icon name="plus" class="size-4" /> Place an Order</x-button><x-button as="a" href="{{ route('customer.orders.index') }}" variant="secondary"><x-icon name="truck" class="size-4" /> My Orders</x-button><x-button as="a" href="{{ route('customer.payments.index') }}" variant="secondary"><x-icon name="credit-card" class="size-4" /> Payment History</x-button></div>

    @if($currentOrder)
        <x-card class="mt-6 overflow-hidden border-primary-100 dark:border-primary-500/20"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div class="flex items-center gap-3"><span class="rounded-2xl bg-primary-50 p-3 text-primary-600 dark:bg-primary-500/10 dark:text-primary-300"><x-icon name="truck" class="size-6" /></span><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Current delivery</p><p class="font-mono text-sm font-bold text-primary-600">{{ $currentOrder->order_code }}</p><p class="mt-1 text-sm text-slate-700 dark:text-slate-300">{{ $currentOrder->product_name }} × {{ $currentOrder->quantity }}</p></div></div><div class="flex items-center gap-3"><x-delivery-status-badge :status="$currentOrder->status" /><x-button as="a" href="{{ route('customer.orders.show', $currentOrder) }}" variant="secondary">Track order <x-icon name="chevron-right" class="size-4" /></x-button></div></div></x-card>
    @endif

    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        <x-card padding="p-0"><div class="flex items-center justify-between px-6 py-4"><div><h2 class="font-heading text-base font-bold text-slate-900 dark:text-white">Recent Orders</h2><p class="text-xs text-slate-400">Track each delivery as it moves forward</p></div><a href="{{ route('customer.orders.index') }}" class="text-sm font-semibold text-primary-600 hover:text-primary-700">View all</a></div><div class="divide-y divide-slate-100 dark:divide-white/5">@forelse($recentOrders as $order)<a href="{{ route('customer.orders.show', $order) }}" class="flex items-center justify-between gap-3 px-6 py-3 transition hover:bg-slate-50 dark:hover:bg-white/5"><div class="min-w-0"><p class="font-mono text-xs font-semibold text-primary-600">{{ $order->order_code }}</p><p class="truncate text-sm font-medium text-slate-900 dark:text-white">{{ $order->product_name }} × {{ $order->quantity }}</p><p class="text-xs text-slate-400">₱{{ number_format($order->total_amount, 2) }}</p></div><x-delivery-status-badge :status="$order->status" /></a>@empty<div class="px-6 pb-6"><x-empty-state icon="truck" title="No orders yet" description="Place your first delivery order when you need water." /></div>@endforelse</div></x-card>
        <x-card padding="p-0"><div class="flex items-center justify-between px-6 py-4"><div><h2 class="font-heading text-base font-bold text-slate-900 dark:text-white">Recent Payments</h2><p class="text-xs text-slate-400">Payments recorded by staff</p></div><a href="{{ route('customer.payments.index') }}" class="text-sm font-semibold text-primary-600 hover:text-primary-700">View all</a></div><div class="divide-y divide-slate-100 dark:divide-white/5">@forelse($recentPayments as $payment)<div class="flex items-center justify-between px-6 py-3"><div><p class="font-mono text-sm font-bold text-success-600 dark:text-success-500">₱{{ number_format($payment->amount, 2) }}</p><p class="text-xs text-slate-400">{{ $payment->payment_date->format('M d, Y') }}</p></div><span class="rounded-xl bg-success-50 p-2 text-success-600 dark:bg-success-500/10 dark:text-success-500"><x-icon name="check-circle" class="size-4" /></span></div>@empty<div class="px-6 pb-6"><x-empty-state icon="credit-card" title="No payments yet" description="Recorded payments will appear here." /></div>@endforelse</div></x-card>
    </div>
</x-layouts.app>
